### ISSUE TITLE
fork for a visual analytics course/advice on teaching

### ISSUE THREAD

**Issue by wesslen** [andrewheiss/datavizf18.classes.andrewheiss.com#1]
Hi Andrew,

Thank you for posting and making your materials of the course available under CC BY-NC-SA 4.0! I'm teaching a graduate (master's) level course in visual analytics in the spring and I'm interested in building off of your materials for my course (of course attributing you for your material, etc.). I'll likely add a lot of the material (my course is 3 hours/week) but the core is definitely there.

I wanted to see if you had any thoughts/advice about the course. Would there be anything different if you would do the next time you teach? How has integration with RStudio.Cloud been? Did you consider using DataCamp to supplement your lectures?

For context, my course is in UNCC's data science master's program -- which consists of business/computer science courses mostly for working professionals. In the past the course has been more computer science focused -- teaching mostly JavaScript/D3/CSS/SVG -- which many of the students, who are not experienced programmers, have found to be very difficult. I'm looking to only teach R/RStudio ecosystem along with RStudio.Cloud.

Thanks for your help,

Ryan

**Comment by andrewheiss** [comment]
Hi!

This is my second time teaching this class, and I've been happy with it both times, even though the workload was different. The first time around (see <https://datavizf17.classes.andrewheiss.com/>) it was only 8 weeks, so I had to compress the material substantially. Students had a weekly assignment + 3 mini projects + 1 final project, and it was a lot of work. But students got a lot more practice with R and several became quite proficient (and a couple are off doing PhD programs now at UNC-CH and Duke).

This time around, I lowered the workload (we don't cover Excel at all; last year we did Excel for the first couple weeks), but it's come at the cost of R practice and proficiency. We're halfway through the semester, and students have only completed three problem sets. So maybe I swung too far the other way? (Even so, some of my current students complain that it feels like 4 or 5 credits, ¯\\\_(ツ)\_/¯ - all we cover now is basic dplyr + lots of ggplot :) ). I don't know what I'll do next time. More R somehow—not crazy levels like the first time, but definitely more than this time.

RStudio.cloud was nice for the first couple weeks, but I transitioned everyone off by week 3 (it was going incredibly slow since a bunch of other classes were also using it, so it was suffering system-wide performance issues).

I didn't consider DataCamp for this class, since it's only 1.5 credit hours, but I do use DataCamp extensively in my 3-credit stats class at <https://statsf18.classes.andrewheiss.com/> (repo: https://github.com/andrewheiss/statsf18.classes.andrewheiss.com), and it's been hit and miss. Some of the DataCamp courses are designed to allow students to skip to different chapters (each DC course consists of 4 chapters), while others definitely don't. I assigned my students chapter 3 of some DC course not knowing that it absolutely required chapters 1 and 2 first, and they were miserably lost and angry.

In that class I also started students on RStudio.cloud but had them transitioned off by week 6.

You mentioned that your course is for working professionals. My stats/data science class is also for working professionals (executive MPA students), and the *absolute biggest hurdle* for the first month or so was basic file system navigation. Dozens hadn't ever made a folder—some access files exclusively through Word's Recent Items menu, and when a file gets pushed out of there, it's effectively gone forever 😱. I assumed they'd be able to make RStudio projects and navigate to them on their computers, but nope. 

ALSO, to get around that, I decided to try distributing pre-structured projects as zip files, and macOS users were fine with that, but Windows makes it exceedingly too easy to not unzip zip files and instead navigate inside them directly. When RStudio on Windows opens a project from within a zip file, it puts it in some temporary folder somewhere and points the working directory to some inaccessible place. I had several students lose their work as Windows performed periodic clean up. It was bad. So now I include detailed instructions about how to create a new project by hand (see <https://statsf18.classes.andrewheiss.com/assignment/04-problem-set/>) (but even then, it takes some students 30+ minutes to do that. 

Good luck! Feel free to steal any of my materials! Let me know how it goes!

**Comment by wesslen** [comment]
Thanks!! This is incredibly helpful. I'll keep this in mind as I'm updating my materials.

One quick snag I've found is my blogdown/hugo skills aren't up to speed. How do you deploy your sites? Netlify?

I found Yihui's bookdown book to be helpful (https://bookdown.org/yihui/blogdown/hugo.html) - are there any other tutorials you'd recommend to learn how to modify, build, and deploy the site?

Thanks again!

**Comment by andrewheiss** [comment]
@apreshill's tutorial is the best I've found: https://alison.rbind.io/post/up-and-running-with-blogdown/

I don't deploy mine on Netlify or GitHub pages. I build the static site locally and then I use `rsync` to upload it to my personal webserver, which I run on [DigitalOcean](https://www.digitalocean.com/). You can see that in the Makefile I have for this site: https://github.com/andrewheiss/datavizf18.classes.andrewheiss.com/blob/master/Makefile

In the terminal tab in RStudio, I run `make deploy` and it builds the site and uploads the public folder.

**Comment by wesslen** [comment]
Thanks!! Closing out as this should get me going. I'll reach back out later on if I have questions. Best of luck with your semester!

**Comment by apreshill** [comment]
Hi!

I have some new-ish materials (mainly slide decks) that go into more depth on deploying to Netlify. Linking here:

1. [Blogdown 1]( https://apreshill.github.io/data-vis-labs-2018/slides/06-slides_blogdown.html#1)
1. [Connecting to GitHub for Blogdown](https://apreshill.github.io/data-vis-labs-2018/slides/07-prework-slides_blogdown.html#1)
1. [2 ways to deploy using Netlify](https://apreshill.github.io/data-vis-labs-2018/slides/07-slides_blogdown_rev.html#1)

**Comment by wesslen** [comment]
@apreshill these materials are AMAZING! I've been working through these materials all day and they're incredibly helpful. Thank you so much for sharing.
